import type { SignInNote } from "../lib/account";

/**
 * Kid-facing copy. New interface text goes here, not inline in components.
 * Short sentences, no blame; technical detail stays out of these strings.
 */
export const text = {
  brand: {
    name: "GameKit",
    tagline: "说出你的游戏，和小助手一起把它做出来",
  },
  header: {
    design: "做游戏",
    code: "看代码",
    project: "项目",
    export: "导出",
    undo: "撤销上一次改动",
    save: { saved: "已保存", saving: "正在保存…", error: "没有保存成功" },
  },
  account: {
    signIn: "登录",
    signOut: "退出",
    checking: "正在确认登录…",
    offline: "现在没联网，小助手暂时休息。做游戏不受影响。",
    unavailable: "登录服务还没准备好。做游戏不受影响。",
    notes: {
      denied: "这个账号还没有开通 GameKit。请让家长或老师帮你开通。",
      failed: "这次没有登录成功，再试一次吧。",
      expired: "登录已经过期了，重新登录就好。",
      unavailable: "登录服务还没准备好。做游戏不受影响。",
      "signed-out": "已经退出登录。你的作品还在这台电脑上。",
    } satisfies Record<SignInNote, string>,
  },
  ai: {
    needsSignIn: "登录后，小助手可以帮你把想法变成游戏。",
    signInToUse: "登录后使用小助手",
    failed: "小助手这次没想好，再试一次吧。",
  },
  stage: {
    idle: "还没开始",
    preparing: "正在准备 pygame 运行环境…",
    loading: "正在载入 pygame-ce…",
    running: "游戏在跑",
    stopped: "停下了",
    failed: "这次没能启动",
    needMain: "还没有 main.py。先去「看代码」新建一个文件吧。",
    play: "试玩我的作品",
    stop: "停下",
    clickToPlay: "点一下画面，键盘和声音才会交给游戏。",
    mine: "正在试玩：你的作品",
    candidate: "正在试玩：小助手做的这一版",
    runtime: (version: string, pybuild: string) => `pygame-ce ${version} · Python ${pybuild}`,
    empty: "这里会出现你的游戏。点「试玩我的作品」就能看到它跑起来。",
  },
  pane: {
    title: "小助手",
    welcome: "先说说你想做一个什么样的游戏吧",
    examples: "比如：「一个在太空里躲陨石的小方块」「一只跑得飞快的狐狸，去追星星」",
    hintPlay: "也可以直接点舞台上的「试玩我的作品」，看看现在的游戏。",
    placeholder: "说说你想做的游戏…",
    placeholderNext: "再说一句：想改哪里？",
    send: "开始做",
    sendNext: "再改一次",
    busy: "小助手正在忙…",
    cancel: "停下这一轮",
    youSaid: "你说",
    current: "现在的作品",
    candidateTitle: "这一版",
    files: (count: number) => `${count} 个文件`,
    changed: (count: number) => `${count} 个文件有改动`,
    showDiff: "看看改了什么",
    adopt: "采用这一版",
    discard: "丢掉这一版",
    adopted: "这一版已经是你的作品了。不满意就点上面的「撤销上一次改动」。",
    discarded: "这一版丢掉了，你的作品没有变。",
    cancelled: "这一轮停下了，你的作品没有变。",
    blocked: "小助手改了几次还是没弄好。你可以在「看代码」里看看，或者换一种说法再试一次。",
    failed: "小助手这次没想好，再试一次吧。",
    unverified: "没能自动看到游戏画面（可能没联网）。你自己在舞台上试玩一下，满意就采用。",
    explainBusy: "正在读代码…",
    doneNotice: "小助手做好了新的一版，去「做游戏」试试。",
  },
  steps: {
    hear: "听懂你的想法",
    design: "设计游戏",
    build: "做出来",
    check: "自动试运行",
    repair: "修好刚发现的问题",
    finish: "可以试玩了",
    stop: "停下了",
  },
  code: {
    files: "文件",
    assets: "素材",
    newFile: "新建文件",
    rename: "改名",
    delete: "删除",
    open: "打开",
    upload: "上传素材",
    generate: "生成素材",
    console: "控制台",
    problems: "问题",
    debug: "调试",
    noProblems: "没有问题。",
    badPath: "这个文件名不能用，换一个吧，例如 game/enemy.py。",
    explain: "讲讲这段",
    binary: "这是二进制素材，不能当代码改。",
    empty: "从左边选一个文件打开。",
    runHint: "在舞台上点一下，键盘才会交给游戏。",
  },
  assets: {
    title: "生成素材",
    copy: "图片先给你看，点「放进项目」才会存进 assets/。",
    kinds: { sprite: "角色", background: "背景", tile: "瓦片", icon: "图标" },
    generate: "生成",
    again: "再生成一张",
    accept: "放进项目",
    close: "关闭",
    busy: "正在画…",
    prompt: "描述你想要的图片，例如：32 像素的小机器人，正面",
  },
  project: {
    name: "名字",
    newSample: "新建示例游戏",
    newBlank: "新建空白项目",
    duplicate: "复制一份",
    exportSource: "导出源码 zip",
    importZip: "导入源码 zip",
    delete: "删除这个项目",
    open: "打开项目",
    switchHint: "换项目会开新的一局对话，作品都在本机。",
    namePrompt: "给新项目起个名字",
    confirmDelete: "删掉这个项目？删了就找不回来了。",
  },
  export: {
    copy: "导出的就是文件，GameKit 不帮你发布。",
    web: "网页 zip",
    webHint: "index.html 加运行文件",
    static: "静态文件夹",
    staticHint: "解压后放到任何地方托管",
    itch: "itch.io 包",
    itchHint: "自己上传的 HTML 项目 zip",
    embed: "嵌入包",
    embedHint: "同一个游戏，再加一个 iframe 页面",
  },
};
