import type { SignInNote } from "../lib/account";

/**
 * Kid-facing copy. New interface text goes here, not inline in components.
 * Short sentences, no blame; technical detail stays out of these strings.
 */
export const text = {
  brand: {
    name: "GameKit",
    tagline: "说出你的游戏，和小助手一起把它做出来",
  },
  header: {
    design: "做游戏",
    code: "看代码",
    project: "项目",
    export: "导出",
    undo: "撤销上一次改动",
    undoShort: "撤销",
    panels: "显示哪些面板",
    panelFiles: "文件栏",
    panelStage: "舞台",
    panelConsole: "控制台",
    save: { saved: "已保存", saving: "正在保存…", error: "没有保存成功" },
    saveHint: "改动会自动保存到这台电脑的浏览器里，不用手动保存。",
  },
  account: {
    signIn: "登录",
    signOut: "退出",
    checking: "正在确认登录…",
    offline: "现在没联网，小助手暂时休息。做游戏不受影响。",
    unavailable: "登录服务还没准备好。做游戏不受影响。",
    notes: {
      denied: "这个账号还没有开通 GameKit。请让家长或老师帮你开通。",
      failed: "这次没有登录成功，再试一次吧。",
      expired: "登录已经过期了，重新登录就好。",
      unavailable: "登录服务还没准备好。做游戏不受影响。",
      "signed-out": "已经退出登录。你的作品还在这台电脑上。",
    } satisfies Record<SignInNote, string>,
  },
  ai: {
    needsSignIn: "登录后，小助手可以帮你把想法变成游戏。",
    signInToUse: "登录后使用小助手",
    failed: "小助手这次没想好，再试一次吧。",
    imageFailed: "这张画没生成成功，再试一次吧。",
    soundFailed: "这个声音没做成功，再试一次吧。",
  },
  stage: {
    idle: "还没开始",
    preparing: "正在准备 pygame 运行环境…",
    loading: "正在载入 pygame-ce…",
    running: "游戏在跑",
    stopped: "停下了",
    failed: "这次没能启动",
    needMain: "还没有 main.py。先去「看代码」新建一个文件吧。",
    play: "试玩我的作品",
    stop: "停下",
    clickToPlay: "点一下画面，键盘和声音才会交给游戏。",
    mine: "正在试玩：你的作品",
    candidate: "正在试玩：小助手做的这一版",
    runtime: (version: string, pybuild: string) => `pygame-ce ${version} · Python ${pybuild}`,
    empty: "这里会出现你的游戏。点「试玩我的作品」就能看到它跑起来。",
  },
  pane: {
    title: "小助手",
    welcome: "先说说你想做一个什么样的游戏吧",
    examples: "比如：「一个在太空里躲陨石的小方块」「一只跑得飞快的狐狸，去追星星」",
    hintPlay: "也可以直接点舞台上的「试玩我的作品」，看看现在的游戏。",
    remembers: "小助手记得你们之前聊过的内容，接着说一句就行。",
    placeholder: "说说你想做的游戏…",
    placeholderNext: "再说一句：想改哪里？",
    send: "开始做",
    sendNext: "再改一次",
    busy: "小助手正在忙…",
    cancel: "停下这一轮",
    voice: "说话",
    voiceLabel: "用说话的方式说出你想做的游戏",
    listening: "正在听你说…",
    voiceDenied: "要听你说，得先允许使用麦克风。",
    voiceFailed: "没听清，再说一次吧。",
    voiceUnsupported: "这个浏览器不支持语音输入，打字也一样。",
    attach: "图片",
    attachLabel: "加一张图片给助手看",
    attachHint: "可以粘贴、选择或拖一张图片进来（拖进输入框）。图片只给这一轮看，不会存进项目。",
    attached: (count: number) => `已加 ${count} 张图片`,
    removeImage: "去掉这张图片",
    imageOnly: "看看这张图，帮我做一个这样的游戏",
    imageFailed: "这张图读不了，换一张试试。",
    youSaid: "你说",
    current: "现在的作品",
    candidateTitle: "这一版",
    files: (count: number) => `${count} 个文件`,
    changed: (count: number) => `${count} 个文件有改动`,
    showDiff: "看看改了什么",
    adopt: "采用这一版",
    discard: "丢掉这一版",
    adopted: "这一版已经是你的作品了。不满意就点上面的「撤销上一次改动」。",
    discarded: "这一版丢掉了，你的作品没有变。",
    cancelled: "这一轮停下了，你的作品没有变。",
    blocked: "小助手改了几次还是没弄好。你可以在「看代码」里看看，或者换一种说法再试一次。",
    failed: "小助手这次没想好，再试一次吧。",
    unverified: "没能自动看到游戏画面（可能没联网）。你自己在舞台上试玩一下，满意就采用。",
    explainBusy: "正在读代码…",
    doneNotice: "小助手做好了新的一版，去「做游戏」试试。",
  },
  steps: {
    hear: "听懂你的想法",
    design: "设计游戏",
    build: "做出来",
    check: "自动试运行",
    repair: "修好刚发现的问题",
    finish: "可以试玩了",
    stop: "停下了",
  },
  /** What the header chip and the pane strip say while a step is running. */
  stepsWorking: {
    hear: "正在听懂你的想法",
    design: "正在设计",
    build: "正在做出来",
    check: "正在试运行",
    repair: "正在修刚发现的问题",
    finish: "马上就好",
    stop: "停下了",
  },
  settings: {
    title: "设置",
    close: "关闭",
    memory: "小助手记得多少",
    memoryHint:
      "小助手会记住你们聊过的内容，下次打开这个项目能接着聊。聊得太长时，它会先把早先的对话缩成一小段摘要，再继续。",
    auto: "自动",
    autoDetail: (modelLimit: number, tokens: number) =>
      `跟随现在的模型（最多约 ${Math.round(modelLimit / 1000)}K，小助手用到 ${Math.round(tokens / 1000)}K）`,
    tokens: (value: number) => `${Math.round(value / 1000)}K`,
    tooBig: (allowed: string) => `模型装不下这么多，会自动用 ${allowed}`,
    current: (tokens: number) => `现在：每个项目最多记 ${Math.round(tokens / 1000)}K`,
  },
  collab: {
    title: "外部协作 (MCP)",
    hint: "开启后，可以在 Cursor、Claude Desktop 或其他支持 MCP 的工具里连接这个项目。外部助手只能查看代码和提出建议，只有你点击「采用这一版」才会真正改写你的作品。",
    badge: "外部协作中",
    badgeTitle: "MCP 外部协作已开启，点击查看设置",
    start: "开启协作",
    stop: "停止协作",
    statusActive: "🟢 协作连接已开启",
    statusInactive: "⚪ 协作连接未开启",
    serverUrl: "MCP 服务地址",
    serverUrlCopy: "复制",
    serverUrlCopied: "已复制！",
    candidateRequest: (tool?: string) => `外部协作建议${tool ? ` (${tool})` : ""}`,
    candidateSay: "外部助手提出了修改建议，请查看代码改动并决定是否采用。",
    needsSignIn: "请先登录再开启外部协作。",
    needsProject: "请先打开一个项目再开启外部协作。",
  },
  code: {
    files: "文件",
    assets: "素材",
    fileCount: (count: number) => `${count} 个文件`,
    assetCount: (count: number) => `${count} 个素材`,
    newFile: "新建文件",
    newFileHint: "新文件叫什么？",
    create: "创建",
    rename: "改名",
    renameHint: "改成什么名字？",
    delete: "删除",
    cancel: "取消",
    upload: "上传",
    uploadHint: "上传图片、声音或字体",
    generate: "生成",
    generateHint: "用小助手生成一张素材",
    console: "控制台",
    problems: "问题",
    debug: "调试",
    noProblems: "没有问题。",
    noFiles: "这个项目还没有文件。新建一个 main.py 就能运行。",
    noAssets: "还没有素材。可以上传图片、声音或字体。",
    badPath: "这个文件名不能用，换一个吧，例如 game/enemy.py。",
    pathTaken: "已经有同名的文件了，换一个名字吧。",
    explain: "讲讲这段",
    binary: "这是二进制素材，不能当代码改。",
    empty: "从左边选一个文件打开。",
    runHint: "在舞台上点一下，键盘才会交给游戏。",
    trash: "回收站",
    trashShow: "展开",
    trashHide: "收起",
    trashEmpty: "回收站是空的。",
    trashEmptyAll: "清空回收站",
    trashEmptied: "回收站清空了。",
    confirmTrash: (name: string) => `把 ${name} 放进回收站？`,
    trashConfirm: "放进回收站",
    confirmPurge: (name: string) => `彻底删掉 ${name}？`,
    purgeConfirm: "彻底删除",
    purge: "彻底删除",
    restore: "恢复",
    trashed: (name: string) => `已经把 ${name} 放进回收站，可以找回来。`,
    restored: (name: string) => `${name} 回来了。`,
  },
  sounds: {
    title: "生成声音",
    /** Sidebar label: short, and never collides with 「生成」 for pictures. */
    entry: "声音",
    copy: "说一句想要什么声音，小助手调好参数，再在浏览器里合成。点「保存到项目」才会存进 assets/。",
    kinds: { sfx: "音效", music: "音乐" },
    promptSfx: "例如：跳起来的声音、捡到金币的声音、撞到墙的声音",
    promptMusic: "例如：太空里的背景音乐、紧张的打怪音乐、轻快的草地音乐",
    generate: "生成",
    again: "再生成一个",
    play: "试听",
    accept: "保存到项目",
    close: "关闭",
    busy: "正在做…",
    seconds: (value: string) => `${value} 秒 · WAV`,
    use: (path: string) => `在代码里这样用：pygame.mixer.Sound("${path}")`,
  },
  assets: {
    title: "生成素材",
    copy: "说一句想要什么，小助手画出来。点「保存到项目」才会存进 assets/。",
    kinds: { sprite: "角色", background: "背景", tile: "瓦片", icon: "图标" },
    size: "大小",
    sizeValue: (px: number) => `${px} 像素`,
    cut: "去掉背景",
    cutHint: "角色和图标会变成背景透明的 PNG。",
    pixel: (width: number, height: number) => `${width}×${height} 像素 · PNG`,
    keepHint: "这张还没有保存。关掉窗口它也会留在这里，下次打开还在。",
    backgroundKept: "这张图没有明显的纯色背景，背景没去干净。可以关掉「去掉背景」，或再生成一张。",
    generate: "生成",
    again: "再生成一张",
    accept: "保存到项目",
    close: "关闭",
    busy: "正在画…",
    prompt: "例如：一只橘色的小狐狸",
  },
  pixel: {
    /** Where the editor is opened from. */
    newImage: "新建图片",
    newImageHint: "从空白画布画一张新图",
    edit: "编辑像素",
    editFile: (name: string) => `编辑像素：${name}`,
    editDraft: "继续修改像素",

    /** 新建图片 dialog */
    newTitle: "新建图片",
    newCopy: "选好大小，从空白画布开始画。画好点「保存」，就会变成 assets/ 里的 PNG。",
    name: "名字",
    nameHint: "会放进 assets/，不用写 .png",
    nameBad: "这个名字不能用，换一个吧，例如 my-image。",
    nameTaken: (path: string) => `已经有叫这个的图了，不会盖掉它。换个名字，或者用 ${path}。`,
    useName: (path: string) => `用 ${path}`,
    size: "大小",
    sizeValue: (px: number) => `${px}×${px}`,
    sizeCustom: "自己填",
    width: "宽",
    height: "高",
    unit: "像素",
    sizeNumber: (side: string) => `${side}要填一个整数，例如 24。`,
    sizeSmall: (side: string) => `${side}最小是 1。`,
    sizeBig: (side: string, limit: number) => `${side}最大是 ${limit}，小一点更好画。`,
    background: "背景",
    transparent: "透明",
    solid: "纯色",
    solidColor: "背景颜色",
    start: "开始画",
    cancel: "取消",

    /** Editor */
    title: "像素编辑器",
    titleFor: (path: string, width: number, height: number) => `${path} · ${width}×${height}`,
    close: "关闭",
    loading: "正在打开…",
    unreadable: "这张图暂时打不开。可以换一张，或者新建一张图重新画。",
    tooBig: "这张图太大了，像素编辑器放不下。",
    tools: "工具",
    pencil: "铅笔",
    pencilHint: "点一下画一个点，按住拖动画线",
    eraser: "橡皮",
    eraserHint: "擦成透明",
    fill: "油漆桶",
    fillHint: "把一片同色的地方涂满",
    picker: "吸管",
    pickerHint: "点图上的颜色，变成当前颜色",
    clear: "清空",
    clearHint: "全部擦成透明，可以撤销",
    undo: "撤销",
    redo: "重做",
    palette: "调色板",
    custom: "自定义颜色",
    transparentColor: "透明",
    current: "当前颜色",
    currentIs: (name: string) => `当前颜色：${name}`,
    customName: (hex: string) => `自定义 ${hex}`,
    grid: "网格线",
    zoomIn: "放大",
    zoomOut: "缩小",
    zoom: (scale: number) => `${scale} 倍`,
    canvas: "画布",
    canvasHint: (width: number, height: number) => `${width}×${height} 的画布，用鼠标、手指或笔来画`,
    preview: "实际大小",
    previewHint: "游戏里看到的样子",

    /** Saving */
    save: "保存",
    saveAs: "另存为新图片",
    saveAsTitle: "另存为新图片",
    saveAsCopy: "原来的图不会变，新图会放进 assets/。",
    saveAsConfirm: "存成新图",
    saving: "正在保存…",
    dirty: "还没保存",
    saved: (path: string) => `已保存到 ${path}`,
    use: (path: string) => `在代码里这样用：pygame.image.load("${path}")`,
    failed: {
      "write-failed": "没存上，浏览器的存储出了点问题。画面还在，再点一次「保存」试试。",
      taken: "已经有同名的图了，不会盖掉它。点「另存为新图片」换个名字。",
      missing: "这张图已经不在项目里了。点「另存为新图片」把它存回来。",
      "bad-path": "这个名字不能用，换一个吧，例如 my-image。",
      "no-project": "这张图不属于现在打开的项目，保存不了。可以先关掉。",
    },

    /** Closing with unsaved changes */
    unsavedTitle: "这张图还没保存",
    unsavedCopy: "关掉的话，刚画的会丢掉。",
    unsavedSave: "保存",
    unsavedDiscard: "不保存",
    unsavedKeep: "继续画",

    colors: {
      "#1a1c2c": "夜空黑",
      "#5d275d": "葡萄紫",
      "#b13e53": "莓果红",
      "#ef7d57": "橘子橙",
      "#ffcd75": "香蕉黄",
      "#a7f070": "嫩草绿",
      "#38b764": "草地绿",
      "#257179": "湖水青",
      "#29366f": "深海蓝",
      "#3b5dc9": "宝蓝",
      "#41a6f6": "天空蓝",
      "#73eff7": "冰蓝",
      "#f4f4f4": "云朵白",
      "#94b0c2": "雾灰",
      "#566c86": "石板灰",
      "#333c57": "夜灰",
      "#000000": "黑色",
      "#ff77a8": "粉红",
      "#8b5a2b": "木头棕",
      "#f2c9a0": "肤色",
    } as Record<string, string>,
  },
  project: {
    title: "我的项目",
    search: "搜索项目名",
    searchEmpty: "没有叫这个名字的项目。",
    empty: "还没有项目。点「新建」做一个吧。",
    newProject: "新建",
    importZip: "导入 zip",
    close: "关闭",
    open: "打开",
    openFirst: "先打开这个项目",
    current: "当前",
    rename: "改名",
    renameHint: "新的项目名",
    duplicate: "复制",
    exportSource: "导出源码",
    delete: "删除",
    confirmDelete: (name: string) => `删掉「${name}」？删了就找不回来了。`,
    deleteConfirm: "删掉",
    cancel: "取消",
    updated: (when: string) => `${when}更新`,
    files: (count: number) => `${count} 个文件`,
    footer: (count: number, where: string) => `${count} 个项目 · 保存在${where}`,
    local: "这台电脑的浏览器里",
    used: (size: string) => `已用 ${size}`,
    namePrompt: "给新项目起个名字",
    switchHint: "换项目会开新的一局对话，作品都在本机。",
  },
  export: {
    copy: "导出的就是文件，GameKit 不帮你发布。",
    web: "网页 zip",
    webHint: "index.html 加运行文件",
    static: "静态文件夹",
    staticHint: "解压后放到任何地方托管",
    itch: "itch.io 包",
    itchHint: "自己上传的 HTML 项目 zip",
    embed: "嵌入包",
    embedHint: "同一个游戏，再加一个 iframe 页面",
  },
};
